name: Build All Projects

on:
  push:
    branches: [ main ]

jobs:
  build-all:
    runs-on: ubuntu-latest

    strategy: 
     matrix: 
      project: [ 
            "CalculatorLite/CalculatorLite.csproj", 
          "PasswordGenerator/PasswordGenerator.csproj",
          "GameOfFunnyColors/GameOfFunnyColors.csproj"
        ]   

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10 Release
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'       
          name: Restore and Build ${{ matrix.project }}
          run: |  
           dotnet restore ${{ matrix.project }}
            dotnet build ${{ matrix.project }} --configuration Release --no-restore --nologo
