name: Build All Projects

on:
  push:
    branches: [ main ]

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10 Preview
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      strategy:
        project: [ "CalculatororLite/CalculatororLite/CalculatororLite.csproj", "PasswordGenerator/PasswordGenerator/PasswordGenerator.csproj" ] 

       name: ${{ format('Restore and Build {0}', matrix.project) }}
  run: |
    dotnet restore ./${{ split(matrix.project, '/')[0] }}/
    dotnet build --configuration Release --no-restore ./${{ split(matrix.project, '/')[0] }}/ --nologo
